---
title: "Bibliography with Annotations"
format: pdf
editor: visual
bibliography: [references.bib, citationExport-bams-d-18-0268.1.xml.bib]
---

## Climate and Atmosphere (Jan 2024+)

[@white2023]

An analysis of the unprecedented heatwave in the PNW in June 2021 looking at how well it was forecast (pretty well) in the days prior and what the impact was in several areas: human impact, marine, forest fire, ag yields, streamflow/hydrology and related landslides due to land change from fire an increased water from melting. NDVI for ag crops showed a marked decrease except for a few crop types. Also specifically addressed the highest temp recorded spot, Lytton, BC and the geographic setting in a dry, rocky valley. The increased likelihood due to climate change is a part of the paper (by Rachel) but also the challenge of exact attribution is significant. We know it is a likely catalyst, though. A key feature in the atmosphere was a "blocking high" and potentially "Arctic amplification" due to a reduced temp gradient from arctic to mid-latitude. More work needed to address causes and frequency.

[@hoskins2015]

This was a doozy of an introduction/review of some of the ideas implicated in extreme weather events in the extratropical regions. I barely got much out of it but it is clear that there is work to be done to connect with amplified Arctic warming, changes in Rossby Wave patterns, blocking, and the physics associated with the PDFs of temperature. Will have to revisit once I have learned more!

[@mckinnon2016]

Read for Rachel group meeting. The authors use a global database of temperatures (Tx and Tn) and focus on the distribution of those temperatures over 1980-2015 for the 30 - 60° N latitude band. They found that most of the distributions across stations do not change shape significantly (minimal change in variance, skew, kurtosis) but do shift positively (warmer mean), with some regional variation. They used quantile linear regression to look at trends across the quantiles for July & August. They also applied PCA to try to get at basis functions that captured the most variance (to compare with the distributional changes in mean/var/skew/kurt) and found that associated Legendre polynomials approximated the primary PCA modes well and would then be independent of the data for an unbiased comparison (apparently). In short, they see the signal of climate warming in the shift of the mean for Tx and Tn and discuss how the change (or not) in the variance regionally relates to extreme events (outliers).

[@white2022]

Could focusing on waveguides that constrain Rossby waves be easier and more successful that trying to forecast extreme events based on Rossby wave connections themselves? Especially when trying to predict events on the S2S time scale. Current evidence suggests persistence of Rossby waves results in quasi-stationary waves that lead to extreme events but our climate models struggle to predict this scenario. But we may have more luck predicting the physical processes that drive Rossby waveguides. On long timescales the relationship between waveguides and meridonally constrained Rossby waves is established but on shorter time scales (monthly/subseasonal) we only have hints of correlation. The authors suggest analysing waveguides in complex GCMs to consider the utility in predicting HWs. It might allow us to sort out how and why Rossby waves become" quasi-stationary, high amplitude, or both". They suggest avenues of research around the theory connecting waveguides -\> Rossby waves, incorporation into models, and perhaps using ML to detect and explain relationships and predictors. Finally, they encourage the researchers in this area to collaborate on both research and terminology.

[@oppenheimer2007]

Short paper criticizing the approach in the (at the time) IPCC report that inflates the confidence in consensus (premature consensus) around predictions for climate change impacts on temp, sea level rise, impacts, and mitigation costs as there is not a full accounting for the uncertainty in the used drivers/evidence applied. Suggests expert review and/or assigned ombudsmen to ensure consistency in reporting uncertainty across working groups especially in areas that are not well understood.

[@barriopedro2023]

Review paper on the current state of HW research. One key takeaway is that there isn't a clear and universal definition of a "heat wave" which inhibits agreement/connection across research approaches. The authors used "periods of at least 3 consecutive days with Tx above the local 95%-ile (1981-2010)" but this emphasizes warm season HWs. The key drivers that have been identified are summarized in figure 8 but also the non-stationary nature of the freq and magnitude of the drivers is a challenge, as is teasing them apart. Great summary of gaps/research areas that need further work around urban HW, marine HW, subseasonal forecasts, and the new efforts to use ML models to augment or replace process-based modeling. Paper is really too long to summarize here so prob should refer to it again.

[@li2023]

Paper compared the outputs of three CMIP6 models in simulations of warm-season marine HWs. Key finding: "By the end of the 21st century, the duration, accumulated heat stress and peak intensity show systematic increases under all the future emission scenarios considered. Conversely, heating rate and the priming period display systematic decreases in the tropics and subtropics". Shorter priming period means corals and kelp have less time to adapt to the rising SST. Some biases found in the modeling and they speculate that they are "caused by different model representations of atmospheric and oceanic processes including(a) cloud formation; (b) deep convection, precipitation and storms, (c) surface winds and associated oceanic heattransport, and (d) ENSO dynamics". Authors recommend using higher resolution models to dive into those processes better.

[@domeisen2022]

Review paper along the lines of Barriopedro (2023) but written in a more accessible language (at least for me) and in shorter format. Heatwave drivers are atmospheric circulation patterns (quasi-stationary waves/Rossby), soil moisture levels, SST anomalies. Can make predictions currently using forecasting models on the scale of \~ few weeks but not beyond that. HWs are expected to become more intense, last longer, and become more frequent, esp in mid-latitudes. In south Asia humid HWs are likely to be especially bad and wet bulb temps may exceed human tolerance in the near future while other areas of the tropics may perpetually be at the limit. There is more work to be done to incorporate the relevant drivers of HWs in models.

[@li2022]

Marine HWs and the impact on coral reefs have been increasing in freq and severity. The authors examine a series of metrics around duration, peak intensity, accumulated heat stress, and heating rates in a SST data set from 1985 - 2019 (CoralTemp x3.1) at a fine resolution of 0.05° x 0.05° and find some overall common features in "warm season" MHWs (increased freq, peak, duration) with some regional differences in accumulation and heating rates. Using multilinear regression and comparing coefficient values they determine that duration rather than magnitude (accumulation) is the primary driver. It is not clear if they normalized their data to avoid problems of scale in the coeffs in comparison. Notable is that they considered two definitions of a MHW event - Maximum Monthly Mean (MMM) as a threshold and also the 90th percentile of historical SSTs (90th %-ile of the 90 highest daily SSTs (3 months) from each year, per grid cell. Days above these thresholds counted as a MHW. They also defined the "year" as a heat stress year (HSY) running from March - Feb in the northern hemisphere and Sept - Aug in the southern. They hypothesize that due to the longer duration relative to potentially lower accumulation some marine ecosystems might have a chance to adapt, especially for regions with a decrease in the heating rate (not true for the northern hemisphere). Also, they caution that the data set they used came from multiple data sources so there could be some inconsistency so they call for a better data set.

[@röthlisberger2023]

The authors divide up the "drivers" of global temperature anomalies (T') into advection, adiabatic warming due to subsidence, diabatic heating (sensible heating?) by deriving a Lagrangian temp anomaly equation from the thermodynamic energy equation that lets them measure the relative contribution of terms related to these three processes. The first look at the PNW 2021 heat wave, and finding consistency, then apply it globally to see regional differences. They also look at the path and time taken for air parcels seen as being involved in the extreme heat and see differences in source distance and speed by region. They conclude that a Lagrangian analysis (following the air) rather than Eulerian (fixed in place) approach is needed to characterize the drivers and their strength. Missing for me is the role of moisture but maybe that is involved in the adiabatic and diabatic effects but I just don't know enough yet.

[@salathé2023]

Paper looks at the PNW and heat extremes since 1950. The find that the hottest days (85th %ile to 99th %ile) are not warming any faster than the median days (50th %ile) during the warm season. Then they use an ensemble WRF model from Mass (2022) for the PNW forced by 12 CMIP5 (RCP8.5) model outputs and find that projecting to 2100 the hottest days WILL experience greater warming rates than the median, depending on location.

[@wehrli2019]

Paper discusses the role of different suspected drivers of heat wave events by using case studies of a few recent events. The use an interesting approach of building the models up from ensembles with a single added component (e.g. soil moisture) to tease out the effect of each and the relative importance. For soil moisture and SST they used both data and prescriptive values in global models with CESM v1.2. They employed "nudging" for atmospheric circulation and wind from ERA-interim and used temperature from Berkeley Earth. For heat waves in regions far from mid-lat and equatorial oceans they found minimal contribution from SSTs, but for all they identify soil moisture and atmospheric circulation as the main drivers in addition to increased forcing from GHGs.

[@luo2024]

Authors track the centroid of heat waves in lat/long and over time to "follow" the heat wave event in 3D and assess frequency, duration, magnitude, and evolution/propagation spatially. The last bit is the especially important part. They used ERA5 as well as MERRA2 and NCEP2 reanalysis data to get at daily max at 2m height. They found that accumulated area of a heat wave is different regionally with more area in the mid-high latitudes in the northern hemisphere vs mid-lat in the southern hemisphere. They believe they are seeing an increase in frequency but a slowing of the moving speed of the heat wave centroid and use CMIP6 simulations to show that these changes are well correlated with increased GHGs and anthropogenic forcing. They found a good match between the metrics they measured from the reanalysis data and the change in those metrics in their simulations.

[@zhang2023a]

The authors model a physical mechanism for a limit on extreme temps at the surface in the mid-latitude land of the N Hemisphere, with a hypothesis that temps can rise until convective instability forces convection and subsequent precipitation, initiating cooling below the threshold. Their model uses $T_{500}$ (500 hPa temp) and some basic thermodynamics (Clausis-Clapyron eqn) and something called the moist static energy (MSE) to identify the point of convective instability and show that the $MSE_{500}$ peaks coincident with the max $T_{s}$ (and also CAPE convective available potential energy) and then use three recent HW events (PNW 2021, WEur 2019, Russ 2010) match their theory using ERA5 data. They find a nice connection with two drivers - an anticyclone (they used potential vorticity, and note that clockwise flow is an anticyclone in the N Hemi) and soil moisture deficit and discuss the relative connection with each driver for the three case study HWs. For the PNW they say that the $T_{500}$ anomaly alone explains the HW intensity from their theory so they say therefore soil moisture deficit played a minor role (without evidence, but just that the temp anomaly explains the $\Delta T$ ). They also connect with changing climate by suggesting the upper bound on $T_{s}$ should increase twice as fast as the global mean surface temp (GMST) although they say $T_{500}$ is increasing at the same rate as GMST. They suggest more research into $T_{500}$ warming is needed along with surface air-specific humidity.

[@stainforth2013]

The authors demonstrate a system for using weather data from stations (collected in a dataset "E-OBS" 0.5$^{\circ}$ x 0.5$^{\circ}$ for Europe) to measure climate change by building the CDF of a sliding 9 year time window and comparing two or more of these time windows. If the smallest change in probability for a given mean temperature (or min temp in winter) is still large over a wide span of years (e.g. 1954-1963 vs 1997-2006) then they assert this is a robust measure of a change in the probability of seeing a new max temperature, indicating a change. They use this approach to get around the non-stationarity of temp distributions under warming. They show that for some regions, like Bordeaux, the change is significant while for others, like Lisbon there is almost no change. The goal is to provide "useful" measures that can be used by policy makers and the public - the probability of seeing a max temperature above X is P. Good paper and well written.

### Season Length Papers

[@wang2021]

The authors analyze HADGHCND data (3.75\$\^\\circ\$ lon x 2.5\$\^\\circ\$ lat) to investigate the apparent length of the seasons for **northern hemisphere land** over 1952-2011 using specific definitions/thresholds for seasonal periods - above 75%-ile of daily mean T2m for summer, below 25%-ile for winter, and spring/fall as the transitions between those two seasons. They found summer increased from 78 - 95 days while the other seasons shortened over 1952-2011. They also used CMIP5 and CMIP6 multi-model sims for SSP2-4.5 & SSP5-8.5, respectively, to look at future season lengths out to 2100. The same overall trends in season lengths persist in the model simulations. Relevant quote "*there is good potential for a 166-days summer and 31-days winter in 2100"* under RCP8.5, which, while seemingly unlikely, is scary.

[@park2021]

Another Northern Hemisphere (NH) focused summer season length study. This one is focused on considering how the summer length, onset, and withdrawal will change under 1.5 and 2.0 \$\^\\circ\$C warming using simulations from the "Half a degree Additional warming Prognosis and Projected Impacts project" (HAPPI) and model projections from CMIP5. They compared 2006-2015 vs projections, using ERA-interim data to compare with the simulations. For smoothing, they fit a fourth harmonic (Fourier series) to remove daily variability and then a 75th percentile threshold for "summer" although they used the HAPPI "All-Hist" runs rather than ERA-interim data itself - instead they compared the HAPPI simulations with ERA-interim and got decent agreement. Summer length increases with warming and is projected to get proportionally longer in the lower latitudes in East Asia and the Mediterranean (near 30 \$\^\\circ\$N) versus higher latitudes in the NH (\> 50 \$\^\\circ\$N). Interestingly, they suggest that someone needs to "investigate summer expansion over oceans" but they haven't published anything on this (but there is a subsequent paper on the Southern Hemisphere out now).

Some key findings:

-   summer season expands by 10 (17) days for 1.5\$\^\\circ\$C (2.0\$\^\\circ\$C)

-   asymmetry in warming rates between early and late summer - for regions that warm early the rate is lower

-   Coastal areas tend to have relatively later onset andwithdrawal than inland areas, indicating its delayed response due to stronger influence of adjacent oceanswith large heat capacity (e.g. Mann and Park 1996).

-   In the added days of onset and withdrawal the number of days warmer than the mean temp increases slightly

-   the impact of similar temperature warming leads to smaller change in summerseason length over high-latitudes than in midlatitudes.

[@park2018]

NH summer length study. The authors used 1953-2012 data from HadGHCND (2.5 x 3.75 lat-lon grid daily) for land from 23.5 deg N to 85 deg N and smoothed grid data for daily mean temp (from max & min temps) using a degree 3 polynomial. Summer onset was when exceeding the 75th percentile in 1953-2012 and withdrawal when dropping below using the intersection of the smoothed curve and the threshold. Found an overall average increase in summer duration of 25 days/60 years or 4.2 days/decade, similar to Wang. Got good correlations between summer temps and the summer indices of onset, duration, and withdrawal. Used CMIP5 experiments to examine future changes (and saw a good match with simulations for the study period as well). They nicely divided up the analysis for regions and saw regional differences (largest change for mediterranean and smallest for USA due to "warming hole" in SE) as well as latitudinal differences (more change at lower lat). They connected some of these changes with internal variability but also used the CMIP5 model results to show these changes in the summer indices cannot be due to internal variability alone but there is a strong forcing from GHG. Very nice visuals - good ideas for my own project. One key finding on coastal areas: "Summer began and ended earlier inland than in coastal areas, from early June to early September and late June to late September, respectively. Strong coastal–inland contrast was identified across the entire NH without notable latitudinal contrast." For me to investigate.

[@lin2021]

The authors combine an analysis of observational and reanalysis data with simulations and projections from CMIP6 models to assess the changing length of summer for the NH. They begin with a nice review of the typical definitions of summer: astronomical, meteorological, synoptic, and using absolute or relative thresholds. They opt for the 75th percentile mean daily temp with 1961-1990 as the baseline period (same as IPCC ref period?), requiring 5 consecutive days above the threshold to start and 5 days below to end summer (no smoothing of the time series!). They used these threshold values for the grid cells and analyzed for 1961-2014. For grid resolution, depending on the data set, they looked at 0.5$^\circ$ up to 3.75$^\circ$ . They saw good agreement between the six different obs/reanalysis data sets in terms of Summer length shape and trend. They tried a range of baseline periods and also saw no sig effect. And, they compared the 75th percentile threshold $T_{75}$ with the $T_{june}$ & $T_{Sept}$ approach of $Pe\tilde{n}a-Ortiz$ et al (2015) \[should read this one\] and saw no significant change in the shape and trend of Summer length vs year. Once they saw this consistency they opted for the Berkeley Earth data for observational T2m and compared with CMIP6 models. An aspect I question is that they said similar trends in changing summer length from CMIP6 model outputs counts as "validation" of the results from observation. They looked at external forcing vs internal variability for driving the change in summer length both regionally and globally. The AMO (+ phase) and PDO (- phase) appear to be associated with regional increases in summer length (according to the authors) although the correlation coefficients are around +0.5 or -0.5 (or worse) at a significance threshold of p = 0.1, so pretty weak, leading them to conclude that external forcing (GHG) is the dominant cause. Next, they use the CMIP6 projections under SSP2-4.5 and SSP5-8.5 to project summer length changes. From the observations they give a changing summer length of 0.39 days/yr for the NH as a whole with some regional differences, and also find that the start/end are extending into the neighboring seasons symmetrically, which is interesting and different from Park et al (2022) and Wang et al (2021). They connect this change with external forcing. Finally, under SSP2-4.5 and SSP5-8.5 they see 0.38 days/yr and 0.59 days/yr growth in the summer length. Two concluding quotes: "There is an obvious relationship between summer length distribution and latitude. The lower the latitude, the longer the summer." (Although they caveat that human activity might buck this trend as it is apparently doing for Europe) and "we also reveal that a 1 $^\circ$C global mean surface temperature increase is associated with 15 days of the summer length increase during 1961-2014 in the observations."

[@weller2020]

Using similar methods to that in Park et al (2018) \[not yet read\] and Park et al (2021) the authors investigate the change in summer length over 1953-2021 for land in the Southern Hemisphere (SH), which includes Southern Africa, Australia, NZ, and the Southern portion of Argentina and Chile (land between 23.5 - 60 $^\circ$S ). For observational data they used Berkeley Earth daily mean temps on a 1x1$^\circ$ grid which they said is best for the SH for coverage of land. They used the 75th percentile 2m temperature as threshold for "summer", although they used the entire analysis period of 1953-2012 to determine that threshold rather than a baseline pre-2000's. They smoothed the time series by using a 4th order harmonic Fourier series and claimed it gives a better RMSE than a 3rd degree polynomial, but they then discuss how this choice has a substantial impact on whether they see symmetry in the rates of early onset versus late withdrawal or asymmetry and didn't convince me that 4th order is truly better - it is simply a choice. To address future changes in summer length due to climate warming, they used CMIP5 experiments with RCP4.5 to confirm agreement with the observational results and then see how summer length would change under that scenario for GHG emission. In general they find that over the 60 yr period, summer begins about 15 days earlier and ends about 13 days later, or a roughly one month lengthening of the summer season. This varies regionally (S Africa shows 47 days longer, while NZ is 4 days longer), and shows some dependence on latitude but I'm not sure they took into account the topography. They found a weak attribution (\~10%, 12% and 5% respectively) to the climate variability caused by IPO and SAM, and say ENSO has minimal impact in the SH. Given the high ratio of coastal area to land in their study area they did look into the changes for coastal areas and found in both the observations and the model results that coastal areas have a later onset and later withdrawal, presumably because of "oceanic thermal capacity". The CMIP5 experiment (ALL forcing) matched their observational results qualitatively but were slightly off on the absolute number of days early/later but from this they conclude that the earlier onset and delayed withdrawal are predominantly caused by anthropogenic forcing.

[@christidis2007]

Read this one because it kept coming up as a source in the other season length papers and I can see why. The authors investigate the length of the "growing season" over 1950-1999 using observational data for land mostly extratropical NH and some small areas of SH with good coverage of Australia (data from HadGHCND (2.5 x 3.75 lat-lon grid daily min & max)) and HadCM3 model outputs for looking at forcing from GHG under various scenarios (like the RCPs but before those were created). They defined the start of the growing season as being above the mean daily temp for the grid cell. Smoothing via 3rd degree polynomial. They found the growing season is lengthening about 2 days/decade on average, with some regional differences (e.g. EU 2.1, NA 1.0) primarily due to an earlier onset of Spring. Using "optimal fingerprint analysis" they show the changes are primarily due to GHG forcing and are able to resolve internal variability. Using the HadCM3 model outputs they predict a continued lengthening that will include later withdrawal of the growing season (or later start of autumn) as well as a slow acceleration to the rate of lengthening of the growing season. One final interesting point - they suggest that the entire growing season isn't warming equally but that the warming at the start is higher due to feedback from earlier snowmelt and cite other sources.

[@mann1996]

[@trenberth1983]

### Full Refs
